license="MIT"
modLoader="javafml"
loaderVersion="47"
issueTrackerURL="https://github.com/DynamicTreesTeam/DynamicTrees/issues"

[[mods]]
modId="dt_sonicraft"
version="${file.jarVersion}"
displayName="Dynamic Trees for SoniCraft"
displayURL="https://www.curseforge.com/minecraft/mc-mods/dynamictrees"
logoFile="pack.png"
credits=""
authors="WenXin2"
description='''
Adds Dynamic Trees compatibility for SoniCraft.
'''

[[dependencies.dt_sonicraft]]
    modId="forge"
    mandatory=true
    versionRange="[47.1.3,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dt_sonicraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dt_sonicraft]]
    modId="dynamictrees"
    mandatory=true
    versionRange="[1.3.6,)"
    ordering="AFTER"
    side="BOTH"
